language: java
os: redhat

services:
  - docker

before_install:
  - jar -cvf Sample1.war META-INF/ WEB-INF/ hello.jsp images/ index.html 
  - docker pull xacaxulu/was-easy-dockerfile:v0.0.1
  - docker run -d -p 80:9080 -p 443:9443 -v Sample1.war:/config/dropins/ xacaxulu/was-easy-dockerfile:v0.0.1
  - docker ps -a



after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push xacaxulu/was-prod-dockerimage:v"$TRAVIS_BUILD_NUMBER";
    fi